services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
      - 'SPRING_JPA_HIBERNATE_DDL_AUTO=update'
    ports:
      - '5432'
    networks:
      - dev

  adminer:
    image: adminer
    restart: always
    ports:
      - 8001:8080
    networks:
      - dev

networks:
  dev:
    driver: bridge


